name: Build flatpak manifest
on:
  pull_request:
    branches:
      - liteloader
  push:
    branches:
      - liteloader
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.runs-on }}
    container:
      # https://github.com/flatpak/flatpak-github-actions?tab=readme-ov-file#docker-image
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    permissions:
      contents: read
    strategy:
      matrix:
        runs-on:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - run: |
          {
            echo -n "arch="
            uname -m
          } >> "$GITHUB_OUTPUT"
        id: arch
          
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: com.qq.QQ-${{ steps.arch.outputs.arch }}.flatpak
          manifest-path: com.qq.QQ.yaml
          arch: ${{ steps.arch.outputs.arch }}
          branch: liteloader

